### ISSUE TITLE
Question: There are no obstacles on rviz (Costmap)

### ISSUE THREAD

**Issue by ChangkiSung** [DLu/navigation_layers#45]
Hi, I am testing range_sensor layer package with ultrasonic sensor.

I can see topic of ultrasonic 

> header: 
>   seq: 11317
>   stamp: 
>     secs: 1537346490
>     nsecs: 819666986
>   frame_id: "/base_ultrasonic_front"
> radiation_type: 0
> field_of_view: 0.261799007654
> min_range: 0.019999999553
> max_range: 0.829999983311
> range: 0.839999973774
> ---

But, I cannot see any obstacles on rviz.

Here is rviz image and costmap_common_param, local_costmap_param and global_costmap_param

![image](https://user-images.githubusercontent.com/28960911/45741895-aa38c000-bc33-11e8-976c-f1e643b4e7cf.png)

-------------------Costmap_common_param----------------
```
#obstacle_range: 3.0 #3.0
#raytrace_range: 3.5 #3.5

#footprint:  [[-0.24,-0.18], [-0.26,-0.16], [-0.26,0.16], [-0.24,0.18], [0.17,0.18], [0.19,0.16], [0.19,-0.16], [0.17,-0.18]] 
footprint:   [[-0.26,-0.18], [-0.26,0.18], [0.19,0.18], [0.19,-0.18]] 
#robot_radius: 0.3



map_type: costmap #voxel #costmap
#observation_sources: scan
#scan: {sensor_frame: base_scan, data_type: LaserScan, topic: scan, marking: true, clearing: true}

obstacle_layer:
  observation_sources: scan
  obstacle_range: 3.0
  raytrace_range: 3.5
  scan: {sensor_frame: base_scan, data_type: LaserScan, topic: scan, marking: true, clearing: true}

sonar_layer:
  topics: ["/ultrasinic/front", "/ultrasinic/left", "/ultrasinic/right"]
  clear_threshold:    0.25
  mark_threshold:     0.46
  no_readings_timeout: 2.0
  clear_on_max_reading: true 


inflation_layer:
  inflation_radius: 0.65 #0.4 1.35
  cost_scaling_factor: 5.0 #0.5 #3.0 
```

---------------Local_costmap_param-----------------------------
```
plugins:
  - {name: obstacle_layer, type: 'costmap_2d::ObstacleLayer'}
  - {name: sonar_layer,   type: "range_sensor_layer::RangeSensorLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}


local_costmap:
  global_frame: /odom
  robot_base_frame: /base_footprint

  update_frequency: 10.0 #5.0 #10.0
  publish_frequency: 10.0 #2.0 #10.0
  transform_tolerance: 0.5  

  static_map: false #false  
  rolling_window: true
  width: 5
  height: 5
  resolution: 0.05

```

----------------Global_costmap_param----------------------------------------
```
plugins:
  - {name: static_layer, type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer, type: 'costmap_2d::ObstacleLayer'}
  - {name: sonar_layer,   type: "range_sensor_layer::RangeSensorLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

global_costmap:
  global_frame: /map
  robot_base_frame: /base_footprint

  update_frequency: 10.0 #1.0 #10.0
  publish_frequency: 10.0 #0.5 #10.0
  transform_tolerance: 0.5

  static_map: true

```
