### ISSUE TITLE
Social navigation layers doesn't appear on rviz

### ISSUE THREAD

**Issue by kadn** [DLu/navigation_layers#54]
I use the plugin proxemiclayer, but I can't get any obstacles on rviz.
```  
 plugins:
      - {name: static_map,       type: "costmap_2d::StaticLayer"}
      - {name: obstacles,        type: "costmap_2d::VoxelLayer"}  
      - {name: inflation_layer,  type: "costmap_2d::InflationLayer"}
      - {name: proxemiclayer,    type: "social_navigation_layers::ProxemicLayer"}
      - {name: passinglayer,     type: "social_navigation_layers::PassingLayer"}
```
I published a people message like following:

```
header: 
  seq: 13225
  stamp: 
    secs: 1560248121
    nsecs: 441350435
  frame_id: "people"
people: 
    name: "liwei"
    position: 
      x: 1.0
      y: 1.0
      z: 0.0
    velocity: 
      x: 0.2
      y: 0.4
      z: 0.0
    reliability: 0.7
    tagnames: []
    tags: []
```
But there is no person information on rviz.
And I'm sure plugin passinglayer is used by global costmap
![111](https://user-images.githubusercontent.com/15666774/59264210-2fa64980-8c75-11e9-8365-92bcff0e5b36.png)
![fff](https://user-images.githubusercontent.com/15666774/59264220-37fe8480-8c75-11e9-922d-ee226af5bd37.png)
