### ISSUE TITLE
Sonar Layer crashing by throwing an exception 'pluginlib::LibraryLoadException

### ISSUE THREAD

**Issue by tahir1069** [DLu/navigation_layers#57]
I am trying to add to add teraranger Evo_mini to my robot and integrating it into ros navigation stack. I have followed all the steps specified. However I am getting an error

	terminate called after throwing an instance of 'pluginlib::LibraryLoadException'  what():  Failed to load library /opt/ros melodic/lib//librange_sensor_layer.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = /opt/ros/melodic/lib//librange_sensor_layer.so: undefined symbol: _ZN10costmap_2d12CostmapLayer9clearAreaEiiii) 

Here is the yml file I have:
```
plugins:  
  - {name: sonar_layer,   type: "range_sensor_layer::RangeSensorLayer"}

sonar_layer:
  topics: ["teraranger_evo_mini/range"]
  clear_threshold: 1.0
  mark_threshold: 8.0
  clear_on_max_reading: true
```
The respective rosparams for the sonar_layer are:
```
/move_base/global_costmap/sonar_layer/clear_on_max_reading
/move_base/global_costmap/sonar_layer/clear_threshold
/move_base/global_costmap/sonar_layer/mark_threshold
/move_base/global_costmap/sonar_layer/no_readings_timeout
/move_base/global_costmap/sonar_layer/topics
/move_base/local_costmap/sonar_layer/clear_on_max_reading
/move_base/local_costmap/sonar_layer/clear_threshold
/move_base/local_costmap/sonar_layer/mark_threshold
/move_base/local_costmap/sonar_layer/no_readings_timeout
/move_base/local_costmap/sonar_layer/topics
```
Can you please share your insights on this.
Thank you so much in advance.
Regards,
Tahir
